- name: uninstall docker
  apt: 
    name: ['docker', 'docker-engine', 'docker.io', 'containerd', 'runc']
    state: absent

# Install Docker CE
# See:
#  * https://github.com/dwdraju/ansible-install-docker
#  * https://docs.docker.com/install/

- name: install required packages for docker-ce
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']
    state: present

- name: add docker's official apt key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_key
  ignore_errors: true

- name: doanload and install docker apt key if apt_key module failed
  shell: "curl -sSL https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg | sudo apt-key add -"
  args:
    warn: no
  when: (add_key is failed)

- name: add docker stable repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
